#! /usr/bin/env ruby

require "date"

gb = ARGV[0].to_i

rep = (gb / 0.075).ceil

date = DateTime.parse("2014-01-01 10:00:00")
puts "generating #{rep} builds for #{gb}GB"
rep.times do |i|
  date += 10
  puts "Generating build ##{i}..."
  system %{script/build}
  system %{script/commit "Did some work and created build ##{i}" "#{date}"}
end
